# Generated by Django 5.1.1 on 2024-10-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_user_is_referred_alter_referral_offered_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
