# Generated by Django 5.1.1 on 2024-10-05 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="offered_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referral",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
