# Generated by Django 5.1.1 on 2024-10-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_alter_referral_offered_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
